class ListSearchTerms {
  
  toArray() {

    // return [
    //   "Móveis usados para comércio zona norte",
    //   "Instalações comerciais zona norte",
    //   "Marcenaria reforma de móveis zona norte",
    //   "Loja de roupas zona norte",
    //   "Moda infantil zona norte",
    //   "Móveis usados para comércio zona sul",
    //   "Instalações comerciais zona sul",
    //   "Ma rcenaria reforma de móveis zona sul",
    //   "Loja de roupas zona sul",
    //   "Moda infantil zona sul",
    //   "Móveis usados para comércio zona leste",
    //   "Instalações comerciais zona leste",
    //   "Marcenaria reforma de móveis zona leste",
    //   "Loja de roupas zona leste",
    //   "Moda infantil zona leste",
    //   "Móveis usados para comércio zona oeste",
    //   "Instalações comerciais zona oeste",
    //   "Marcenaria reforma de móveis zona oeste",
    //   "Loja de roupas zona oeste",
    //   "Moda infantil zona oeste",
    //   "Móveis usados para comércio Guarulhos",
    //   "Instalações comerciais Guarulhos",
    //   "Marcenaria reforma de móveis Guarulhos",
    //   "Loja de roupas Guarulhos",
    //   "Moda infantil Guarulhos",
    //   "Móveis usados para comércio Osasco",
    //   "Instalações comerciais Osasco",
    //   "Marcenaria reforma de móveis Osasco",
    //   "Loja de roupas Osasco",
    //   "Moda infantil Osasco",
    //   "Móveis usados para comércio Santo André",
    //   "Instalações comerciais Santo André",
    //   "Marcenaria reforma de móveis Santo André",
    //   "Loja de roupas Santo André",
    //   "Moda infantil Santo André",
    //   "Móveis usados para comércio São Bernardo do Campo",
    //   "Instalações comerciais São Bernardo do Campo",
    //   "Marcenaria reforma de móveis São Bernardo do Campo",
    //   "Loja de roupas São Bernardo do Campo",
    //   "Moda infantil São Bernardo do Campo",
    //   "Móveis usados para comércio São Caetano do Sul",
    //   "Instalações comerciais São Caetano do Sul",
    //   "Marcenaria reforma de móveis São Caetano do Sul",
    //   "Loja de roupas São Caetano do Sul",
    //   "Moda infantil São Caetano do Sul",
    //   "Móveis usados para comércio Mogi das Cruzes",
    //   "Instalações comerciais Mogi das Cruzes",
    //   "Marcenaria reforma de móveis Mogi das Cruzes",
    //   "Loja de roupas Mogi das Cruzes",
    //   "Moda infantil Mogi das Cruzes",
    //   "Móveis usados para comércio Carapicuíba",
    //   "Instalações comerciais Carapicuíba",
    //   "Marcenaria reforma de móveis Carapicuíba",
    //   "Loja de roupas Carapicuíba",
    //   "Moda infantil Carapicuíba",
    // ];

    return [
      "Móveis usados zona norte",
      "Móveis usados zona sul",
      "Móveis usados zona leste",
      "Móveis usados zona oeste",
      "Móveis usados Guarulhos",
      "Móveis usados Osasco",
      "Móveis usados Santo André",
      "Móveis usados São Bernardo do Campo",
      "Móveis usados São Caetano do Sul",
      "Móveis usados Mogi das Cruzes",
      "Móveis usados Carapicuíba",
    ];

  }

}

module.exports = ListSearchTerms;